# Student Exam Analyser
# Analyzing 30 students exam and grads using Pandas and Numpy
# Libraries Pandas, Numpy

In [19]:
# Importing Libraries
import pandas as pd
import numpy as np

In [20]:
# Generating Data
np.random.seed(42)
random_scores = np.random.randint(40, 100, size = 30)
random_scores
student_name = np.array("Ade")
student_name

array('Ade', dtype='<U3')

In [21]:
# Generating DataFrame from Data
student_data = pd.DataFrame({"Names" : student_name, "Scores" : random_scores})
student_data

   Names  Scores
0    Ade      78
1    Ade      91
2    Ade      68
3    Ade      54
4    Ade      82
5    Ade      47
6    Ade      60
7    Ade      78
8    Ade      97
9    Ade      58
10   Ade      62
11   Ade      50
12   Ade      50
13   Ade      63
14   Ade      92
15   Ade      75
16   Ade      79
17   Ade      63
18   Ade      42
19   Ade      61
20   Ade      92
21   Ade      41
22   Ade      63
23   Ade      83
24   Ade      69
25   Ade      77
26   Ade      41
27   Ade      99
28   Ade      60
29   Ade      72

In [22]:
# Generating Data Mean,Min, Max and Standard Deviation
student_data["Scores"].mean()
student_data["Scores"].min()
student_data["Scores"].max()
student_data["Scores"].std()

np.float64(16.79220536199877)

In [23]:
# Generating assign grades function
def assign_grades (score):
    if score >= 80:
        return "A"
    elif score >= 65 and score < 80:
        return "B"
    elif score >= 50 and score < 65:
        return "C"
    elif score < 50:
        return "F"

In [24]:
#Generating grades on the Dataframe from the assign grades function
student_data["Grades"] = student_data["Scores"].apply(assign_grades)
student_data

   Names  Scores Grades
0    Ade      78      B
1    Ade      91      A
2    Ade      68      B
3    Ade      54      C
4    Ade      82      A
5    Ade      47      F
6    Ade      60      C
7    Ade      78      B
8    Ade      97      A
9    Ade      58      C
10   Ade      62      C
11   Ade      50      C
12   Ade      50      C
13   Ade      63      C
14   Ade      92      A
15   Ade      75      B
16   Ade      79      B
17   Ade      63      C
18   Ade      42      F
19   Ade      61      C
20   Ade      92      A
21   Ade      41      F
22   Ade      63      C
23   Ade      83      A
24   Ade      69      B
25   Ade      77      B
26   Ade      41      F
27   Ade      99      A
28   Ade      60      C
29   Ade      72      B

In [25]:
# Generating the grade counter
grade_count = student_data["Grades"].value_counts().sort_index()
grade_count

Grades
A     7
B     8
C    11
F     4
Name: count, dtype: int64